import os
import io
import datetime
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch


def generate_security_investigation_pdf(scan_data: Dict[str, Any]) -> bytes:
    """
    Generate an enterprise-grade PDF Security Investigation Report.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Heading1'],
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        'ReportSubtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=14
    )
    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=12,
        spaceAfter=6
    )
    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['Normal'],
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#334155")
    )
    callout_style = ParagraphStyle(
        'CalloutText',
        parent=styles['Normal'],
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#0f172a")
    )

    story = []

    # 1. Header Banner
    story.append(Paragraph("AI CYBERSECURITY THREAT INVESTIGATION REPORT", title_style))
    timestamp_str = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    story.append(Paragraph(f"Generated by Antigravity Autonomous SOC Agent | Timestamp: {timestamp_str}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#3b82f6"), spaceAfter=12))

    # 2. Executive Summary Box
    url = scan_data.get("url", "https://example.com")
    risk_score = scan_data.get("risk_score", 0)
    threat_level = scan_data.get("threat_level", "SAFE")
    classification = scan_data.get("classification", "Safe")
    attack_type = scan_data.get("attack_type", "None")
    targeted_brand = scan_data.get("targeted_brand", "None")
    confidence = scan_data.get("confidence_percentage", 95.0)

    # Risk badge background color
    if risk_score >= 70:
        badge_bg = colors.HexColor("#fee2e2")
        badge_fg = colors.HexColor("#b91c1c")
    elif risk_score >= 45:
        badge_bg = colors.HexColor("#fef3c7")
        badge_fg = colors.HexColor("#b45309")
    else:
        badge_bg = colors.HexColor("#dcfce7")
        badge_fg = colors.HexColor("#15803d")

    summary_data = [
        [
            Paragraph(f"<b>Target URL:</b><br/>{url[:60]}", body_style),
            Paragraph(f"<b>Risk Score:</b><br/><font size='14' color='{badge_fg.hexval()}'><b>{risk_score} / 100</b></font>", body_style),
            Paragraph(f"<b>Threat Level:</b><br/><font color='{badge_fg.hexval()}'><b>{threat_level}</b></font>", body_style)
        ],
        [
            Paragraph(f"<b>Classification:</b> {classification} ({confidence}% conf)", body_style),
            Paragraph(f"<b>Attack Category:</b> {attack_type}", body_style),
            Paragraph(f"<b>Targeted Brand:</b> {targeted_brand}", body_style)
        ]
    ]

    summary_table = Table(summary_data, colWidths=[240, 140, 140])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#cbd5e1")),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 12))

    # 3. AI Cybersecurity Investigator Explanation
    story.append(Paragraph("Autonomous AI Analyst Reasoning & Threat Assessment", section_heading))
    ai_explanation = scan_data.get("ai_explanation", "No explanation available.")
    story.append(Paragraph(ai_explanation, body_style))
    story.append(Spacer(1, 10))

    # 4. Multi-Factor Risk Breakdown
    story.append(Paragraph("Multimodal Risk Breakdown", section_heading))
    breakdown = scan_data.get("breakdown", {})
    breakdown_data = [
        ["Dimension", "Risk Rating", "Evaluated Security Posture"],
        ["URL Lexical / ML", f"{breakdown.get('url_risk', 0)}%", "Entropy, subdomains, token obfuscation, and homoglyphs"],
        ["Domain Infrastructure", f"{breakdown.get('domain_risk', 0)}%", "WHOIS registration maturity and newly registered domain (NRD) check"],
        ["Content Forensics", f"{breakdown.get('content_risk', 0)}%", "Credential input fields, hidden iframes, and fake login forms"],
        ["Brand Impersonation", f"{breakdown.get('reputation_risk', 0)}%", "Fuzzy similarity, typo-squatting, and deceptive subdomain matching"],
        ["Cryptographic Transport", f"{breakdown.get('visual_risk', 0)}%", "SSL/TLS validity, certificate authority trust chain, and protocol"]
    ]

    breakdown_table = Table(breakdown_data, colWidths=[140, 90, 290])
    breakdown_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1e293b")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")])
    ]))
    story.append(breakdown_table)
    story.append(Spacer(1, 12))

    # 5. Detected Evidence & Indicators
    story.append(Paragraph("Forensic Indicators & Technical Evidence", section_heading))
    evidence_list = scan_data.get("evidence", [])
    if evidence_list:
        ev_data = [["Severity", "Category", "Indicator Findings"]]
        for ev in evidence_list[:6]:
            sev = ev.get("severity", "LOW")
            ev_data.append([
                Paragraph(f"<b>{sev}</b>", body_style),
                Paragraph(ev.get("category", "General"), body_style),
                Paragraph(f"<b>{ev.get('title')}</b>: {ev.get('description')}", body_style)
            ])
        ev_table = Table(ev_data, colWidths=[70, 120, 330])
        ev_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0f172a")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(ev_table)
    story.append(Spacer(1, 12))

    # 6. Actionable Security Recommendations
    story.append(Paragraph("Actionable SOC & User Security Recommendations", section_heading))
    recommendations = scan_data.get("recommendations", [])
    for idx, rec in enumerate(recommendations, 1):
        story.append(Paragraph(f"<b>{idx}.</b> {rec}", body_style))
        story.append(Spacer(1, 3))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
